config/routes.rb
Notifiy::Application.routes.draw do
  devise_for :users, :path => "users", :path_names => { 
    :sign_in => 'login', 
    :sign_out => 'logout', 
    :password => 'secret', 
    :confirmation => 'verification', 
    :unlock => 'unblock', 
    :registration => 'register', 
    :sign_up => 'sign_up' 
  }
  resources :users
  
  post 'pusher/auth'

  resources :messages
  root :to => "home#index"
  
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :recipient_id, :sender_id
  belongs_to :sender, :foreign_key => :sender_id, :class_name => 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, :class_name => 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  validates_presence_of :name
  
  has_many :received_messages, :class_name => 'Message', :foreign_key => :recipient_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @messages = current_user.received_messages
  end
  
  def create
    message = Message.new(params[:message])
    message.sender_id = current_user.id
    if message.save
      flash[:notice] = "you created a message"
      redirect_to '/'
      
      # Send a Pusher notification
      Pusher['private-'+params[:message][:recipient_id]].trigger('new_message', {:from => current_user.name, :subject => message.subject})
    else
      @user = User.find(params[:message][:recipient_id])
      render :action => 'users/show'
    end
  end
  
end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  protect_from_forgery :except => :auth # stop rails CSRF protection for this action
  
  def auth
    if current_user && params[:channel_name] == "private-#{current_user.id}"
      response = Pusher[params[:channel_name]].authenticate(params[:socket_id])
      render :json => response
    else
      render :text => "Not authorized", :status => '403'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :only => 'show'
  
  
  def show
    @user =  User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% if signed_in? %>
<h2>All the users of BookFace</h2>

<%= render :partial => User.all %>

<% else %>
 <h2>Only logged in users can use BookFace</h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notifiy</title>
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
  
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
  <script src="http://js.pusherapp.com/1.9/pusher.min.js"></script>
  <script src="/javascripts/jquery.titlealert.js"></script>
  
	<% if signed_in? # no notifications if you're not signed in %>
  <script type="text/javascript" charset="utf-8">
    $(function() {
      var pusher = new Pusher('6a4e2a45f8d9137231f6'); // Replace with your app key
      var channel = pusher.subscribe('private-'+<%= current_user ? current_user.id : 'null' %>);
      
      channel.bind('new_message', function(data) {
        msg = data.from + ' has sent you a message: ' + data.subject;
        dom_notify(msg);
        title_notify(msg);
        if (window.webkitNotifications) { webkit_notify(msg); }
      });
      
      // In DOM alert
      function dom_notify(msg) {
        $('#notify').text(msg);
        $('#notify').fadeIn();
        setTimeout(function() {
          $('#notify').fadeOut
          ();
        }, 2000);
      }
      
      // <title> msg
      function title_notify(msg) {
        $.titleAlert(msg);
      }
      
      // Webkit Notifications API
      // http://www.html5rocks.com/en/tutorials/notifications/quick/
      
      // Setup permissions
      if (window.webkitNotifications) {
        console.log("Notifications are supported!");
        $('#notify_api').show();
      }
      else {
        console.log("Notifications are not supported for this Browser/OS version yet.");
      }
      
      $('#ask_notify_permission').click(function() {
        window.webkitNotifications.requestPermission();
      });
      
      // Notify function
      function webkit_notify(msg) {
        notify = window.webkitNotifications.createNotification('http://pusher.com/stylesheets/images/feature_scalable.png', msg, '');
        notify.show();
      }
      
      // Some useful Pusher debug msgs
      pusher.connection.bind('connecting', function() {
        $('div#status').text('Connecting to Pusher...');
      });
      pusher.connection.bind('connected', function() {
        $('div#status').text('Connected to Pusher!');
      });
      pusher.connection.bind('failed', function() {
        $('div#status').text('Connection to Pusher failed :(');
      });
      channel.bind('subscription_error', function(status) {
        $('div#status').text('Pusher subscription_error');
      });
    });
  </script>
	<% end %>
</head>
<body>
	<% if signed_in? %>
  <div id="notify">A little notification here</div>
  
  <div id="status"></div>
  
  <div id="notify_api"><button type="button" id="ask_notify_permission">Enable Webkit Notifications</button></div>
	<% end %>

	
	
	<div class="holder">
	  <h1><%= link_to 'BookFace', '/' %></h1>

  	<div class="nav">	
  		<% if user_signed_in? %>
  			<%= link_to 'your messages', messages_path %>
  			<%= link_to 'logout', destroy_user_session_path %>
  		<% else %>
  			<%= link_to 'login', new_user_session_path %>
  			<%= link_to 'register', new_user_registration_path %>
  		<% end %>
  	</div>
  	
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		<%= yield %>
	</div>
	
</body>
</html>

app/views/messages/_message.html.erb
<div class="message_item">
<h3><%= message.subject %></h3>

<p>From <%= message.sender.name %> <%= time_ago_in_words(message.created_at) %> ago</p>

<p><%= message.body %></p>

</div>

app/views/messages/index.html.erb
<h2>Your messages</h2>

<% if @messages.any? %>
<%= render :partial => @messages %>
<% else %>
<p>How sad, you have no messages.</p>
<% end %>

app/views/users/_user.html.erb
<p><%= link_to user.name, user %></p>

app/views/users/show.html.erb
<h2><%= @user.name %>'s page</h2>

<% form_for Message.new do |f| %>
	<%= f.hidden_field :recipient_id, :value => @user.id %>
	<div>
		<label for="message_subject">Subject</label>
		<%= f.text_field :subject %>
	</div>
	<div>
		<label for="message_body">Message</label>
		<%= f.text_area :body %>
	</div>
	<div>
		<%= f.submit 'Send a message' %>
	</div>
<% end %>